### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by AtiyaLatif** [SumonaMukho/MulticlassClassificationPerformanceScores#1]
When i run thye code i gave it arguments in the mian cod fine

Mian: myMultiClassConf(testLabels,predictedLabels)

Error:

Operator ':' is not supported for operands of type 'categorical'.

Error in myMultiClassConf (line 4)
for i = (1:num_labels)

Error in main (line 103)
myMultiClassConf(testLabels,predictedLabels)

please tell me how to fix this

**Comment by SumMuk** [comment]
`num_labels` means the number of classes for example for a three class problem, `num_labels = 3`. For example, let 

`cm_mat = [100,  0, 0;
                     20,   60, 20;
                     2,      0 ,  98];

then calling the function:

`[TPR, TNR, TP, FP, FN, TN,F1_score,MCC,PRECISION, Overall_Result] = myMultiClassConf(cm_mat,3)`

would give the following answer
```
TPR =

    1.0000    0.6000    0.9800


TNR =

    0.8900    1.0000    0.9000


TP =

   100    60    98


FP =

    22     0    20


FN =

     0    40     2


TN =

   178   200   180


F1_score =

    0.9009    0.7500    0.8991


MCC =

    0.8541    0.7071    0.8492


PRECISION =

    0.8197    1.0000    0.8305


Overall_Result = 

  struct with fields:

                       Sensitivity: 0.8600
                       Specificity: 0.9300
                         Precision: 0.8834
                 FalsePositiveRate: 0.0700
                          F1_score: 0.8500
    MatthewsCorrelationCoefficient: 0.8035
```
